
Newsfooter = [u"공식 SNS 통하니 트위터 미투데이  구독신청 한겨레신문 한겨레Copyrights  한겨레신문사 무단전재 및 재배포 금지한겨레는 한국온라인신문협회www.kona.or.kr의 디지털뉴스이용규칙에 따른 저작권을 행사합니다.",
              u"JTBC DramaHouse  J Content Hub의 모든 콘텐트기사는 저작권법의 보호를 받은바 무단 전재 복사 배포 등을 금합니다.Copyright by JTBC DramaHouse  JcontentHub Co. Ltd. All Rights Reserved.",
              u"저작권자c MBC www.imnews.com 무단복제재배포 금지",
              u"공식 SNS SBSNews 트위터 페이스북 저작권자 SBSSBS콘텐츠허브 무단복제재배포 금지",
              u"pcwyna.co.kr연합뉴스앱궁금한배틀Y화보포토무비저작권자c 연합뉴스 무단 전재재배포 금지",
              u"OSEN표재민",
              u"동영상 뉴스앵커",
              u"동영상 뉴스",
              u"사진제공MBC",
              u"한겨레",
              u"MBC",
              u"뉴스데스크 앵커",
              u"OSEN 전주",
              u"서울연합뉴스",
              u"머니투데이",
              u"스타뉴스",
              u"서울뉴시스",
              u"사진제공",
              u"목포전남세월호",
              u"울릉도뉴스1",
              u"EPA연합뉴스",
              u"안산연합뉴스",
              u"뉴스1",
              u"News1",
              u"TV리포트",
              u"뉴스데스크",
              u"사진SBS",
              u"연합뉴스",
              u"방송화면",
              u"OSEN",
              u"스포츠동아",
              u"스포츠동아DB",
              u"마이데일리",
              u"뉴시스",
              u"오마이뉴스",
              u"지디넷코리아",
              u"AP연합뉴스",
              u"뉴스분석",
              u"앵커멘트"]

Javascript = [u"// flash 오류를 우회하기 위한 함수 추가",
              u"function _flash_removeCallback() {}"]